kind: Service
apiVersion: v1
metadata:
  name: infomedia-landing
  namespace: infomedia    
spec:
  selector:
    app: infomedia-landing
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infomedia-landing
  namespace: infomedia 
  labels:
    app: infomedia-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infomedia-landing
  template:
    metadata:
      labels:
        app: infomedia-landing
      annotations:
        # Annotations to configure Prometheus.
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port:  "8080"          
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: infomedia-landing
        image:  ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          timeoutSeconds: 5
          periodSeconds: 60
          failureThreshold: 2      
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "200Mi"
            cpu: "0.001"
          limits:
            memory: "400Mi"
            
      nodeSelector:
        whitelisted: "true"


---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-infomedia-landing
  namespace: infomedia 
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 100
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infomedia-landing
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 0.1
  - type: Pods
    pods:
      metric:
        name: rate_jvm_memory_used_bytes_2m
        selector: {}
      target:
        type: AverageValue
        averageValue: 200Mi

  - type: Pods
    pods:
      metric:
        name: rate_http_server_requests_2m
        selector: {}
      target:
        type: AverageValue
        averageValue: 50